const{test, expect} = require('@playwright/test');
test('Validate the Order Overview Details.', async({page})=>{
 await page.goto ('https://www.saucedemo.com/');
await page.getByPlaceholder('Username').fill('standard_user');
await page.getByPlaceholder('Password').fill('secret_sauce');
await page.getByRole('button', {name: 'Login'}).click();
expect(page).toHaveURL('https://www.saucedemo.com/inventory.html');
await page.locator('#add-to-cart-sauce-labs-backpack').click();
await (page.locator('.shopping_cart_link')).click();
expect(page).toHaveURL('https://www.saucedemo.com/cart.html');
await page.getByRole('button', {name: 'Checkout'}).click();
await page.getByPlaceholder('First Name').fill('Test');
await page.getByPlaceholder('Last Name').fill('Test');
await page.getByPlaceholder('Zip/Postal Code').fill('123456');
await page.getByRole('button', {name: 'Continue'}).click();
await expect(page.getByText('Checkout: Overview')).toBeVisible();
await expect(page.getByText('QTY')).toBeVisible();
await expect(page.getByText('Description')).toBeVisible();
// await expect(page.getByText('1')).toBeVisible();
await expect(page.getByText('Sauce Labs Backpack')).toBeVisible();
await expect(page.getByText('carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.')).toBeVisible();
await expect(page.locator('.inventory_item_price')).toBeVisible('$29.99');
await expect(page.getByText('Payment Information:')).toBeVisible();
await expect(page.locator('[data-test="payment-info-value"]')).toBeVisible('SauceCard #31337');
await expect(page.getByText('Shipping Information:')).toBeVisible();
await expect(page.locator('[data-test="shipping-info-value"]')).toBeVisible('Free Pony Express Delivery!');
await expect(page.getByText('Price Total')).toBeVisible();
await expect(page.locator('.summary_subtotal_label')).toBeVisible('Item total: $29.99');
await expect(page.getByText('Tax: $2.40')).toBeVisible();
await expect(page.getByText('Total: $32.39')).toBeVisible();
await page.waitForTimeout(2000);
});