const{test, expect} = require('@playwright/test');
const { LoginPage } = ('../pages/SauceDemo/LoginPage');
const {CustomerDetailPage} = ('../pages/SauceDemoCustomerDetailPage');
const {OverviewPage} = ('../pages/SauceDemo/OverviewPage');
const {InventryPage} = ('../pages/SauceDemo/InventryPage');
const {CartPage} = ('../pages/SauceDemo/CartPage');

test('Validate the Order Overview Details.', async({page})=>{
 const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.login('standard_user', 'secret_sauce');
const inventryPage = new InventryPage(page);
    await inventryPage.goto();
    await inventryPage.addToCart('Sauce Labs Backpack');
    await inventryPage.openCart();
await page.getByRole('button', {name: 'Checkout'}).click();
const customerDetailPage = new CustomerDetailPage(page);
await customerDetailPage.goto();
await customerDetailPage.submitDetail('test', 'test2', '123456');
const overviewPage = new OverviewPage(page);
await expect(page.getByText('Checkout: Overview')).toBeVisible();
await overviewPage.goto();
await overviewPage.verifyProductDetails('Sauce Labs Bike Light');
await expect(page.getByText('Payment Information:')).toBeVisible();
await expect(page.locator('[data-test="payment-info-value"]')).toBeVisible('SauceCard #31337');
await expect(page.getByText('Shipping Information:')).toBeVisible();
await expect(page.locator('[data-test="shipping-info-value"]')).toBeVisible('Free Pony Express Delivery!');
await expect(page.getByText('Price Total')).toBeVisible();
await expect(page.locator('.summary_subtotal_label')).toBeVisible('Item total: $29.99');
await expect(page.getByText('Tax: $2.40')).toBeVisible();
await expect(page.getByText('Total: $32.39')).toBeVisible();
await page.waitForTimeout(2000);
});